In [1]:
import sys
sys.version

'3.9.19 | packaged by conda-forge | (main, Mar 20 2024, 12:38:46) [MSC v.1929 64 bit (AMD64)]'

In [2]:
import torch
torch.__version__

'1.12.0'

In [4]:
t1 = torch.tensor([1, 2, 3])
t1

tensor([1, 2, 3])

In [5]:
import numpy as np
array1 = np.arange(12).reshape(3, 4)
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
t2 = torch.tensor(array1)
t2

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=torch.int32)

In [7]:
# 空数组
torch.empty([3, 4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
# 全为1的数组
torch.ones([3, 4])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
# 全为0的数组
torch.zeros([3, 4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
# 给定范围的随机数
torch.randint(low=0, high=10, size=[3, 4])

tensor([[7, 0, 6, 5],
        [3, 1, 9, 7],
        [4, 3, 1, 0]])

In [11]:
# 0到1的随机数
torch.rand([3, 4])

tensor([[0.2484, 0.9715, 0.0735, 0.2107],
        [0.1994, 0.6661, 0.7921, 0.5672],
        [0.9025, 0.4343, 0.3549, 0.4757]])

In [12]:
# 当tensor里面只有一个元素的时候，可以直接用item方法取出来，多个元素不能这样子用
torch.tensor([3]).item()

3

In [13]:
t2.numpy()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
t2.size()

torch.Size([3, 4])

In [15]:
t2.size(1)

4

In [16]:
t3 = torch.arange(12)
t3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
t3.view(3, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [18]:
# -1表示根据前面的来确定，保证乘积一样即可
t3.view(2, -1)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [19]:
# view是浅拷贝，不影响本来的
t3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
t3.dim()

1

In [21]:
t3.view(3, 4).dim()

2

In [22]:
t3.reshape([3, 4]).dim()

2

In [23]:
t3.max()

tensor(11)

In [24]:
t3.min()

tensor(0)

In [27]:
# 求标准差
t3.float().std()

tensor(3.6056)

In [28]:
t3.reshape([3, 4]).t()

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [30]:
from torch import float32

t4 = torch.tensor(np.arange(24).reshape(2, 3, 4), dtype=float32)
t4

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [32]:
t4.dtype

torch.float32

In [33]:
# 3x2x4
t4.transpose(0, 1)

tensor([[[ 0.,  1.,  2.,  3.],
         [12., 13., 14., 15.]],

        [[ 4.,  5.,  6.,  7.],
         [16., 17., 18., 19.]],

        [[ 8.,  9., 10., 11.],
         [20., 21., 22., 23.]]])

In [34]:
# 4x3x2
t4.transpose(0, 2)

tensor([[[ 0., 12.],
         [ 4., 16.],
         [ 8., 20.]],

        [[ 1., 13.],
         [ 5., 17.],
         [ 9., 21.]],

        [[ 2., 14.],
         [ 6., 18.],
         [10., 22.]],

        [[ 3., 15.],
         [ 7., 19.],
         [11., 23.]]])

In [35]:
# 2x4x3
t4.transpose(1, 2)

tensor([[[ 0.,  4.,  8.],
         [ 1.,  5.,  9.],
         [ 2.,  6., 10.],
         [ 3.,  7., 11.]],

        [[12., 16., 20.],
         [13., 17., 21.],
         [14., 18., 22.],
         [15., 19., 23.]]])

In [36]:
# t4
t4.permute(0, 1, 2)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [37]:
# # 3x2x4
t4.permute(1, 0, 2)

tensor([[[ 0.,  1.,  2.,  3.],
         [12., 13., 14., 15.]],

        [[ 4.,  5.,  6.,  7.],
         [16., 17., 18., 19.]],

        [[ 8.,  9., 10., 11.],
         [20., 21., 22., 23.]]])

In [38]:
t4

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])