In [1]:
import torch
import numpy as np

In [2]:
t1 = torch.tensor(np.arange(24).reshape([2, 3, 4]))
t1

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]], dtype=torch.int32)

In [4]:
# 取出23
t1[1, 2, 3]

tensor(23, dtype=torch.int32)

In [5]:
t1[1]

tensor([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]], dtype=torch.int32)

In [6]:
# 加冒号表示全取
t1[1, :, :]

tensor([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]], dtype=torch.int32)

In [7]:
t1.double()

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]], dtype=torch.float64)

In [9]:
t1.dtype

torch.int32

In [10]:
torch.cuda.is_available()

False

In [11]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')